// content/services.ts
export type Service = {
  key: string;
  name: string;
  unit: string;
  slugCost: string;
  intro: string;
  drivers: string[];
  included: string[];
  notIncluded: string[];
};

export const SERVICES: Service[] = [
  {
    key: "junk-removal",
    name: "Junk Removal",
    unit: "job",
    slugCost: "junk-removal-cost",
    intro: "Junk removal pricing usually depends on volume, weight, access, and disposal fees.",
    drivers: ["Truck volume or load size", "Heavy items (concrete, dirt, appliances)", "Stairs/elevator access", "Distance to disposal site"],
    included: ["Labor to load items", "Haul-away and disposal", "Basic cleanup after loading"],
    notIncluded: ["Hazardous waste handling", "Major demolition work", "Permits (if required)"],
  },
  {
    key: "moving-help",
    name: "Moving Help",
    unit: "hour",
    slugCost: "moving-help-cost",
    intro: "Moving help is often billed hourly and varies by crew size, truck needs, and stairs.",
    drivers: ["Crew size", "Stairs/elevator", "Long carries and parking distance", "Packing/unpacking add-ons"],
    included: ["Loading/unloading labor", "Basic furniture handling"],
    notIncluded: ["Truck rental", "Packing supplies", "Long-distance transport"],
  },
  {
    key: "house-cleaning",
    name: "House Cleaning",
    unit: "hour",
    slugCost: "house-cleaning-cost",
    intro: "Cleaning costs depend on home size, condition, and how deep the clean is.",
    drivers: ["Sq ft / number of rooms", "Deep clean vs maintenance", "Pets and buildup", "Frequency (one-time vs recurring)"],
    included: ["Standard surface cleaning", "Bathrooms and kitchen cleaning"],
    notIncluded: ["Carpet shampooing", "Mold remediation", "Exterior window washing"],
  },
  {
    key: "handyman",
    name: "Handyman",
    unit: "hour",
    slugCost: "handyman-cost",
    intro: "Handyman pricing varies by skill, materials, and the complexity of the job.",
    drivers: ["Task complexity", "Materials required", "Time minimums", "Urgent/same-day requests"],
    included: ["Labor for typical repairs/installs"],
    notIncluded: ["Licensed electrical/plumbing work where required", "Major structural work"],
  },
  {
    key: "yard-cleanup",
    name: "Yard Cleanup",
    unit: "job",
    slugCost: "yard-cleanup-cost",
    intro: "Yard cleanup is usually priced by labor, debris volume, and hauling/disposal.",
    drivers: ["Lot size", "Debris volume", "Haul-away required", "Seasonality (leaf season)"],
    included: ["Raking, bagging, light trimming", "Debris consolidation"],
    notIncluded: ["Tree removal", "Stump grinding", "Major landscaping installs"],
  },
  {
    key: "pressure-washing",
    name: "Pressure Washing",
    unit: "sq_ft",
    slugCost: "pressure-washing-cost",
    intro: "Pressure washing costs typically depend on surface area and stain severity.",
    drivers: ["Total sq ft", "Oil/rust stains", "Multi-story access", "Water availability"],
    included: ["Standard wash of target area"],
    notIncluded: ["Sealing/coating", "Repairs to surface damage"],
  },
  {
    key: "carpet-cleaning",
    name: "Carpet Cleaning",
    unit: "room",
    slugCost: "carpet-cleaning-cost",
    intro: "Carpet cleaning pricing often scales by rooms, stain treatment, and fiber type.",
    drivers: ["Rooms and square footage", "Stain/pet treatment", "High-traffic areas", "Dry time / method"],
    included: ["Standard cleaning per room"],
    notIncluded: ["Flood restoration", "Carpet repairs"],
  },
  {
    key: "pest-control",
    name: "Pest Control",
    unit: "visit",
    slugCost: "pest-control-cost",
    intro: "Pest control costs depend on pest type, infestation level, and follow-up visits.",
    drivers: ["Pest type", "Home size", "One-time vs plan", "Access to crawlspaces/attic"],
    included: ["Inspection and treatment"],
    notIncluded: ["Structural repairs", "Exclusion work unless quoted"],
  },
  {
    key: "appliance-repair",
    name: "Appliance Repair",
    unit: "repair",
    slugCost: "appliance-repair-cost",
    intro: "Repair pricing depends on diagnosis time, parts, and appliance type.",
    drivers: ["Appliance type", "Parts cost and availability", "Labor minimums", "Age of appliance"],
    included: ["Diagnosis + repair labor (varies by provider)"],
    notIncluded: ["Major replacement parts unless quoted"],
  },
  {
    key: "dumpster-rental",
    name: "Dumpster Rental",
    unit: "week",
    slugCost: "dumpster-rental-cost",
    intro: "Dumpster rental costs depend on size, weight limits, and rental duration.",
    drivers: ["Dumpster size", "Overage weight fees", "Rental duration", "Permits (street placement)"],
    included: ["Drop-off and pickup", "Included tonnage (varies)"],
    notIncluded: ["Overage fees", "Extended rental fees"],
  },
  {
    key: "gutter-cleaning",
    name: "Gutter Cleaning",
    unit: "linear_ft",
    slugCost: "gutter-cleaning-cost",
    intro: "Gutter cleaning pricing scales with linear feet, height, and roof access.",
    drivers: ["Linear feet", "Home height", "Guards installed", "Debris level"],
    included: ["Clearing gutters and downspouts (typical)"],
    notIncluded: ["Repairs or new installs"],
  },
  {
    key: "electrician",
    name: "Electrician",
    unit: "hour",
    slugCost: "electrician-cost",
    intro: "Electrician rates vary by license level, complexity, and service call minimums.",
    drivers: ["Service call minimum", "Panel/rewire complexity", "Permit/inspection needs", "Urgency"],
    included: ["Labor for electrical work"],
    notIncluded: ["Fixtures/materials unless quoted"],
  },
  {
    key: "plumbing",
    name: "Plumbing",
    unit: "hour",
    slugCost: "plumbing-cost",
    intro: "Plumbing rates vary by issue severity, access, and emergency scheduling.",
    drivers: ["Diagnosis complexity", "Access (slab/wall)", "Emergency calls", "Parts required"],
    included: ["Labor for typical plumbing repairs"],
    notIncluded: ["Major remodel piping", "Fixtures unless quoted"],
  },
  {
    key: "garage-door-repair",
    name: "Garage Door Repair",
    unit: "repair",
    slugCost: "garage-door-repair-cost",
    intro: "Garage door repair prices depend on springs, tracks, openers, and door type.",
    drivers: ["Spring replacement", "Opener repair/replacement", "Door size/type", "Safety sensors"],
    included: ["Repair labor and adjustments (varies)"],
    notIncluded: ["New door installs unless quoted"],
  },
  {
    key: "leaf-removal",
    name: "Leaf Removal",
    unit: "job",
    slugCost: "leaf-removal-cost",
    intro: "Leaf removal costs depend on yard size, leaf volume, and haul-away needs.",
    drivers: ["Lot size", "Leaf volume", "Bagging vs mulching", "Haul-away"],
    included: ["Raking/blowing and collection (typical)"],
    notIncluded: ["Tree trimming", "Gutter cleaning unless quoted"],
  },
];
